config/routes.rb
Rails.application.routes.draw do
  root to: 'surveys#index'
  resources :surveys do
    resources :questions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  validates :name, presence: true
  validates_length_of :name, maximum: 100
  before_save(:titleize_question)

  private
    def titleize_question
      self.name = self.name.titleize
    end
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 100
  before_save(:titleize_survey)

  private
    def titleize_survey
      self.name = self.name.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new
    render :new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new(question_params)
    if @question.save
      redirect_to survey_path(@survey)
    else
      render :new
    end
  end

  def show
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :show
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to survey_path(@question.survey)
    else
      @survey = Survey.find(params[:survey_id])
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to survey_path(@question.survey)
  end

  private
  def question_params
    params.require(:question).permit(:name, :question)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
    render :index
  end

  def new
    @survey = Survey.new
    render :new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to surveys_path
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
    render :edit
  end

  def show
    @survey = Survey.find(params[:id])
    render :show
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to surveys_path
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_path
  end

  private
  def survey_params
    params.require(:survey).permit(:name, :genre)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>you are idoit:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_question_form.html.erb
<%= render "layouts/errors", :object => @question %>
<%= form_for [@survey, @question] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :question %>
  <%= f.text_area :question %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_survey_form.html.erb
<%= render "layouts/errors", :object => @survey %>
<%= form_for @survey do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <div class="jumbotron">
  <h1>IvE gOt A qUeStIoN fOr YoU kId</h1> 
  </div>
    <%= yield %>
  </div>
    </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit player:</h1>

<%= render "layouts/question_form" %>

app/views/questions/new.html.erb
<h1>Add a new question:</h1>

<%= render "layouts/question_form" %>

app/views/questions/show.html.erb
<h1>Question: <%= @question.name %></h1>
<h3> <%= @question.question %></h3>

<p><%= link_to "Edit question", edit_survey_question_path(@survey, @question) %></p>
<p><%= link_to "Delete question", survey_question_path(@survey, @question),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<form id="question">
<input type="radio" id="answer_1" name="question1" value="1" />
<label for="answer1">option 1</label>
<input type="radio" id="answer_2" name="question1" value="2" />
<label for="answer2">option 2</label>
<input type="radio" id="answer_3" name="question1" value="3" />
<label for="answer3">option 3</label>
<input type="radio" id="answer_4" name="question1" value="4" />
<label for="answer4">option 4</label>
</form>
                                       
<p><%= link_to "Return to survey", survey_path(@survey) %></p>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% if @surveys.any? %>
  <ul>
    <% @surveys.each do |survey| %>
      <li><%= link_to survey.name, survey_path(survey) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There aren't any surveys.</p>
<% end %>


<p><%= link_to "Add new survey", new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>
<h3><%= @survey.genre %></h3>

<% if @survey.questions.any? %>
  <h4>Here are the questions for this survey:</h4>

  <% @survey.questions.each do |question| %>
    <ul>
      <li>
        <%= link_to question.name, survey_question_path(@survey, question) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No questions are on this survey.</p>
<% end %>

<p><%= link_to "Add a question", new_survey_question_path(@survey) %></p>

<p><%= link_to "Edit", edit_survey_path(@survey) %></p>
<p><%= link_to "Delete survey", survey_path(@survey),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to surveys", surveys_path %></p>